"""Write tbm-pin.json into each storefront demo folder, then collect drive-sites.json."""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEMO = ROOT / "public" / "demo"
BASE = "https://texasbullmarketing.com/demo"

# Storefronts only. Service-area demos are intentionally absent.
PINS = [
    {
        "folder": "FarmhausTable",
        "id": "farmhaus-table",
        "name": "Farmhaus Table",
        "type": "restaurant",
        "schemaType": "Restaurant",
        "phone": "+12107750020",
        "street": "2239 FM 3432",
        "city": "Adkins",
        "region": "TX",
        "zip": "78101",
        "lat": 29.3105642,
        "lng": -98.2074925,
        "spanish": "optional",
    },
    {
        "folder": "JSAutoShop",
        "id": "js-auto",
        "name": "J's Auto Shop",
        "type": "auto-repair",
        "schemaType": "AutoRepair",
        "phone": "+12107449275",
        "street": "9154 Aqua Dr",
        "city": "Boerne",
        "region": "TX",
        "zip": "78006",
        "lat": 29.7946641,
        "lng": -98.7319703,
        "spanish": "required",
    },
    {
        "folder": "ArMandosPizzeria",
        "id": "armandos-pizzeria",
        "name": "ArMando's Pizzeria",
        "type": "restaurant",
        "schemaType": "Restaurant",
        "phone": "+18305817023",
        "street": "13250 U.S. Highway 87 West, Suite A",
        "city": "La Vernia",
        "region": "TX",
        "zip": "78121",
        "lat": 29.3560654,
        "lng": -98.1167879,
        "spanish": "optional",
    },
    {
        "folder": "BaldysAmericanDiner",
        "id": "baldys-diner",
        "name": "Baldy's American Diner",
        "type": "restaurant",
        "schemaType": "Restaurant",
        "phone": "+18309473580",
        "street": "9356 US Hwy 87 W",
        "city": "La Vernia",
        "region": "TX",
        "zip": "78121",
        "lat": 29.308346,
        "lng": -98.08377,
        "spanish": "optional",
    },
    {
        "folder": "CasasMetal",
        "id": "casas-metal",
        "name": "Casas Custom Metal Buildings",
        "type": "signs-other",
        "schemaType": "HomeAndConstructionBusiness",
        "phone": "+12108356561",
        "street": "260 Great Oaks Blvd",
        "city": "La Vernia",
        "region": "TX",
        "zip": "78121",
        "lat": 29.3486934,
        "lng": -98.033859,
        "spanish": "required",
    },
    {
        "folder": "GMNails",
        "id": "gm-nails",
        "name": "GM Nails and Spa",
        "type": "spa",
        "schemaType": "HealthAndBeautyBusiness",
        "phone": "+18304993394",
        "street": "2543 FM 775",
        "city": "La Vernia",
        "region": "TX",
        "zip": "78121",
        "lat": 29.3502102,
        "lng": -98.127536,
        "spanish": "optional",
    },
    {
        "folder": "LaVerniaChinese",
        "id": "la-vernia-chinese",
        "name": "La Vernia Chinese Cuisine",
        "type": "restaurant",
        "schemaType": "Restaurant",
        "phone": "+18307794800",
        "street": "11727 U.S. Hwy 87 W",
        "city": "La Vernia",
        "region": "TX",
        "zip": "78121",
        "lat": 29.3387328,
        "lng": -98.1020781,
        "spanish": "optional",
    },
    {
        "folder": "Rice2Go",
        "id": "rice-2-go",
        "name": "Rice 2 Go",
        "type": "restaurant",
        "schemaType": "Restaurant",
        "phone": "+18303917423",
        "street": "225 Chihuahua St",
        "city": "La Vernia",
        "region": "TX",
        "zip": "78121",
        "lat": 29.3533601,
        "lng": -98.1096695,
        "spanish": "optional",
    },
    {
        "folder": "SammysPawsAndSpas",
        "id": "sammys-paws",
        "name": "Sammy's Paws and Spas",
        "type": "spa",
        "schemaType": "LocalBusiness",
        "phone": "+12108857802",
        "street": "120 Wild Stallion Dr",
        "city": "La Vernia",
        "region": "TX",
        "zip": "78121",
        "lat": 29.2932512,
        "lng": -98.1196304,
        "spanish": "optional",
    },
    {
        "folder": "TacoVallarta",
        "id": "taco-vallarta",
        "name": "Taco Vallarta",
        "type": "restaurant",
        "schemaType": "Restaurant",
        "phone": "+18305817013",
        "street": "14021 U.S. Hwy 87 W",
        "city": "La Vernia",
        "region": "TX",
        "zip": "78121",
        "lat": 29.3568676,
        "lng": -98.1293289,
        "spanish": "optional",
    },
    {
        "folder": "TheShed",
        "id": "the-shed",
        "name": "The Shed",
        "type": "restaurant",
        "schemaType": "CafeOrCoffeeShop",
        "phone": "+12109990160",
        "street": "102 San Antonio Rd",
        "city": "La Vernia",
        "region": "TX",
        "zip": "78121",
        "lat": 29.3556161,
        "lng": -98.1190665,
        "spanish": "optional",
    },
    {
        "folder": "TexasBistro",
        "id": "texas-bistro",
        "name": "Texas Bistro",
        "type": "restaurant",
        "schemaType": "Restaurant",
        "phone": "+18303027538",
        "street": "1932 S Seguin Ave",
        "city": "New Braunfels",
        "region": "TX",
        "zip": "78130",
        "lat": 29.6877844,
        "lng": -98.1083084,
        "spanish": "optional",
    },
    {
        "folder": "CRTireShop",
        "id": "cr-tire-shop",
        "name": "CR Tire Shop",
        "type": "auto-repair",
        "schemaType": "AutoRepair",
        "phone": "+18307425353",
        "street": "211 W Central Ave",
        "city": "Nixon",
        "region": "TX",
        "zip": "78140",
        "lat": 29.2667991,
        "lng": -97.7665535,
        "spanish": "required",
    },
    {
        "folder": "DiamondRCoffeeCo",
        "id": "diamond-r-coffee",
        "name": "Diamond R Coffee Co.",
        "type": "restaurant",
        "schemaType": "CafeOrCoffeeShop",
        "phone": "+18302030531",
        "street": "804 Texas 80",
        "city": "Nixon",
        "region": "TX",
        "zip": "78140",
        "lat": 29.2826937,
        "lng": -97.7652326,
        "spanish": "optional",
    },
    {
        "folder": "ElRodeo",
        "id": "el-rodeo",
        "name": "El Rodeo Mexican Restaurant",
        "type": "restaurant",
        "schemaType": "Restaurant",
        "phone": "+18305822150",
        "street": "109 E Central Ave",
        "city": "Nixon",
        "region": "TX",
        "zip": "78140",
        "lat": 29.2675,
        "lng": -97.7639,
        "spanish": "optional",
    },
    {
        "folder": "LaEnchiladita",
        "id": "la-enchiladita",
        "name": "La Enchiladita",
        "type": "restaurant",
        "schemaType": "Restaurant",
        "phone": "+18305821147",
        "street": "105 W 2nd St",
        "city": "Nixon",
        "region": "TX",
        "zip": "78140",
        "lat": 29.2682299,
        "lng": -97.7650253,
        "spanish": "optional",
    },
    {
        "folder": "TheLuckyTeaCup",
        "id": "lucky-tea-cup",
        "name": "The Lucky Tea Cup",
        "type": "restaurant",
        "schemaType": "Restaurant",
        "phone": "+17138344943",
        "street": "219 N Nixon Ave",
        "city": "Nixon",
        "region": "TX",
        "zip": "78140",
        "lat": 29.2690502,
        "lng": -97.7649295,
        "spanish": "optional",
    },
    {
        "folder": "TaqueriaLaGuadalupana",
        "id": "taqueria-la-guadalupana",
        "name": "Taqueria La Guadalupana",
        "type": "restaurant",
        "schemaType": "Restaurant",
        "phone": "+18305822371",
        "street": "1000 E Central Ave",
        "city": "Nixon",
        "region": "TX",
        "zip": "78140",
        "lat": 29.2701792,
        "lng": -97.7546537,
        "spanish": "optional",
    },
    {
        "folder": "ElValleDeMexico",
        "id": "el-valle",
        "name": "El Valle De Mexico",
        "type": "restaurant",
        "schemaType": "Restaurant",
        "phone": "+12107263070",
        "street": "10081 TX-106 Loop",
        "city": "San Antonio",
        "region": "TX",
        "zip": "78263",
        "lat": 29.3743866,
        "lng": -98.2890644,
        "spanish": "optional",
    },
    {
        "folder": "AutoWorxV2",
        "id": "auto-worx",
        "name": "Auto Worx",
        "type": "auto-repair",
        "schemaType": "AutoRepair",
        "phone": "+18303037775",
        "street": "960 E Court",
        "city": "Seguin",
        "region": "TX",
        "zip": "78155",
        "lat": 29.5691299,
        "lng": -97.9534853,
        "spanish": "required",
    },
    {
        "folder": "MendozasAutoRepair",
        "id": "mendozas-auto",
        "name": "Mendoza's Auto Repair",
        "type": "auto-repair",
        "schemaType": "AutoRepair",
        "phone": "+18305342025",
        "street": "571 W. Kingsbury",
        "city": "Seguin",
        "region": "TX",
        "zip": "78155",
        "lat": 29.5803716,
        "lng": -97.9722272,
        "spanish": "required",
    },
    {
        "folder": "MichoacanaPremium",
        "id": "michoacana",
        "name": "Michoacana Premium",
        "type": "restaurant",
        "schemaType": "IceCreamShop",
        "phone": "+18303595555",
        "street": "1447 E Court St",
        "city": "Seguin",
        "region": "TX",
        "zip": "78155",
        "lat": 29.569173,
        "lng": -97.9485162,
        "spanish": "optional",
    },
    {
        "folder": "TaqueriaAtotonilco",
        "id": "taqueria-atotonilco",
        "name": "Taqueria Atotonilco",
        "type": "restaurant",
        "schemaType": "Restaurant",
        "phone": "+18304334668",
        "street": "744 W Kingsbury St",
        "city": "Seguin",
        "region": "TX",
        "zip": "78155",
        "lat": 29.5807372,
        "lng": -97.9747445,
        "spanish": "optional",
    },
    {
        "folder": "The1908RestaurantBar",
        "id": "the-1908",
        "name": "The 1908 Restaurant + Bar",
        "type": "restaurant-high",
        "schemaType": "Restaurant",
        "phone": "+18308326726",
        "street": "100 E Court St",
        "city": "Seguin",
        "region": "TX",
        "zip": "78155",
        "lat": 29.569,
        "lng": -97.964484,
        "spanish": "optional",
    },
    {
        "folder": "TheBlackdoorSteakhouse",
        "id": "blackdoor",
        "name": "The Blackdoor Steakhouse",
        "type": "restaurant-high",
        "schemaType": "Restaurant",
        "phone": "+18304915556",
        "street": "104 N Austin St",
        "city": "Seguin",
        "region": "TX",
        "zip": "78155",
        "lat": 29.5690593,
        "lng": -97.9647247,
        "spanish": "optional",
    },
]


def main() -> None:
    n = 0
    for row in PINS:
        folder = DEMO / row["folder"]
        if not folder.is_dir():
            print("missing folder", folder)
            sys.exit(1)
        pin = {k: v for k, v in row.items() if k != "folder"}
        pin["demoUrl"] = f"{BASE}/{row['folder']}/"
        (folder / "tbm-pin.json").write_text(
            json.dumps(pin, indent=2) + "\n", encoding="utf-8"
        )
        n += 1
        print("wrote", folder / "tbm-pin.json")
    print("pins", n)
    subprocess.check_call([sys.executable, str(ROOT / "scripts" / "collect-drive-sites.py")])


if __name__ == "__main__":
    main()
